/**
 * Application Constants
 * Centralizes UI constants, language definitions, and translation thresholds.
 */

export const ON_DEMAND_FALLBACK_COUNT = 4;

export const SUPPORTED_TARGET_LANGUAGES = [
  { code: 'en', name: 'English', color: '#3b82f6' },
  { code: 'es', name: 'Spanish (Español)', color: '#ef4444' },
  { code: 'fr', name: 'French (Français)', color: '#8b5cf6' },
  { code: 'de', name: 'German (Deutsch)', color: '#f59e0b' },
  { code: 'it', name: 'Italian (Italiano)', color: '#10b981' },
  { code: 'pt', name: 'Portuguese (Português)', color: '#06b6d4' },
  { code: 'ru', name: 'Russian (Русский)', color: '#ec4899' },
  { code: 'ja', name: 'Japanese (日本語)', color: '#f43f5e' },
  { code: 'ko', name: 'Korean (한국어)', color: '#6366f1' },
  { code: 'zh-CN', name: 'Chinese Simplified (简体中文)', color: '#e11d48' },
  { code: 'zh-TW', name: 'Chinese Traditional (繁體中文)', color: '#ea580c' },
  { code: 'ar', name: 'Arabic (العربية)', color: '#14b8a6' },
  { code: 'he', name: 'Hebrew (עברית)', color: '#0284c7' },
  { code: 'hi', name: 'Hindi (हिन्दी)', color: '#d97706' },
  { code: 'tr', name: 'Turkish (Türkçe)', color: '#be123c' },
  { code: 'nl', name: 'Dutch (Nederlands)', color: '#84cc16' },
  { code: 'pl', name: 'Polish (Polski)', color: '#a855f7' },
  { code: 'sv', name: 'Swedish (Svenska)', color: '#0ea5e9' },
  { code: 'no', name: 'Norwegian (Norsk)', color: '#38bdf8' },
  { code: 'da', name: 'Danish (Dansk)', color: '#f43f5e' },
  { code: 'fi', name: 'Finnish (Suomi)', color: '#0284c7' },
  { code: 'vi', name: 'Vietnamese (Tiếng Việt)', color: '#10b981' },
  { code: 'th', name: 'Thai (ไทย)', color: '#ca8a04' },
  { code: 'el', name: 'Greek (Ελληνικά)', color: '#2563eb' },
  { code: 'uk', name: 'Ukrainian (Українська)', color: '#eab308' },
  { code: 'cs', name: 'Czech (Čeština)', color: '#059669' },
  { code: 'ro', name: 'Romanian (Română)', color: '#f97316' },
  { code: 'hu', name: 'Hungarian (Magyar)', color: '#10b981' },
  { code: 'id', name: 'Indonesian (Bahasa Indonesia)', color: '#ef4444' },
  { code: 'ms', name: 'Malay (Bahasa Melayu)', color: '#06b6d4' },
  { code: 'tl', name: 'Tagalog / Filipino', color: '#8b5cf6' },
  { code: 'bn', name: 'Bengali (বাংলা)', color: '#10b981' },
  { code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ)', color: '#f59e0b' },
  { code: 'mr', name: 'Marathi (मराठी)', color: '#ea580c' },
  { code: 'gu', name: 'Gujarati (ગુજરાતી)', color: '#06b6d4' },
  { code: 'ta', name: 'Tamil (தமிழ்)', color: '#ec4899' },
  { code: 'te', name: 'Telugu (తెలుగు)', color: '#6366f1' },
  { code: 'kn', name: 'Kannada (ಕನ್ನಡ)', color: '#eab308' },
  { code: 'ml', name: 'Malayalam (മലയാളം)', color: '#14b8a6' },
  { code: 'ur', name: 'Urdu (اردو)', color: '#059669' },
  { code: 'fa', name: 'Persian (فارسی)', color: '#d97706' },
  { code: 'bg', name: 'Bulgarian (Български)', color: '#10b981' },
  { code: 'hr', name: 'Croatian (Hrvatski)', color: '#3b82f6' },
  { code: 'sr', name: 'Serbian (Српски)', color: '#ef4444' },
  { code: 'sk', name: 'Slovak (Slovenčina)', color: '#8b5cf6' },
  { code: 'sl', name: 'Slovenian (Slovenščina)', color: '#06b6d4' },
  { code: 'lt', name: 'Lithuanian (Lietuvių)', color: '#eab308' },
  { code: 'lv', name: 'Latvian (Latviešu)', color: '#be123c' },
  { code: 'et', name: 'Estonian (Eesti)', color: '#3b82f6' },
  { code: 'ca', name: 'Catalan (Català)', color: '#f59e0b' },
  { code: 'eu', name: 'Basque (Euskara)', color: '#059669' },
  { code: 'gl', name: 'Galician (Galego)', color: '#0ea5e9' },
  { code: 'ga', name: 'Irish (Gaeilge)', color: '#10b981' },
  { code: 'cy', name: 'Welsh (Cymraeg)', color: '#ef4444' },
  { code: 'is', name: 'Icelandic (Íslenska)', color: '#2563eb' },
  { code: 'sw', name: 'Swahili (Kiswahili)', color: '#14b8a6' },
  { code: 'af', name: 'Afrikaans', color: '#f97316' },
  { code: 'hy', name: 'Armenian (Հայերեն)', color: '#8b5cf6' },
  { code: 'ka', name: 'Georgian (ქართული)', color: '#be123c' },
  { code: 'az', name: 'Azerbaijani (Azərbaycan)', color: '#06b6d4' },
  { code: 'kk', name: 'Kazakh (Қазақ)', color: '#0ea5e9' },
  { code: 'uz', name: 'Uzbek (Oʻzbek)', color: '#10b981' },
  { code: 'mn', name: 'Mongolian (Монгол)', color: '#ef4444' },
  { code: 'ne', name: 'Nepali (नेपाली)', color: '#ec4899' },
  { code: 'si', name: 'Sinhala (සිංහල)', color: '#d97706' },
  { code: 'my', name: 'Burmese (မြန်မာ)', color: '#f59e0b' },
  { code: 'km', name: 'Khmer (ខ្មែរ)', color: '#2563eb' },
  { code: 'lo', name: 'Lao (ລາວ)', color: '#059669' },
  { code: 'sq', name: 'Albanian (Shqip)', color: '#be123c' },
  { code: 'mk', name: 'Macedonian (Македонски)', color: '#eab308' },
  { code: 'bs', name: 'Bosnian (Bosanski)', color: '#3b82f6' },
  { code: 'mt', name: 'Maltese (Malti)', color: '#ef4444' },
  { code: 'la', name: 'Latin (Latina)', color: '#8b5cf6' },
  { code: 'eo', name: 'Esperanto', color: '#10b981' },
  { code: 'yi', name: 'Yiddish (ייִדיש)', color: '#6366f1' },
];
